{{- if .Values.redis.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-crud.redisSecretName" . }}
  namespace: {{ include "user-crud.namespaceName" . }}
type: Opaque
data:
  password: {{ .Values.redis.auth }}
{{- end -}}