apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-crud.fullname" . }}
  labels:
    {{- include "user-crud.labels" . | nindent 4 }}
  namespace: {{ include "user-crud.namespaceName" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "user-crud.selectorLabels" . | nindent 4 }}
