apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-crud-deployment
  namespace: user
  labels:
    app: users-crud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-crud
  template:
    metadata:
      labels:
        app: users-crud
    spec:
      containers:
      - name: users-crud
        image: gcr.io/reflecting-surf-381016/user-crud:latest
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /user/health
            port: http
        readinessProbe:
          httpGet:
            path: /user/health
            port: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: REDIS_HOST
          value: "10.41.204.59"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "test-redis"
        - name: ORDER_SERVICE
          value: "order-crud-service"
        - name: ORDER_NAMESPACE
          value: "order"
      serviceAccountName: user-sa
