apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-crud-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80